

using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson.Serialization.IdGenerators;
using MongoDB.Bson;
using OrderCaptureAPI.Services;
using System;

namespace OrderCaptureAPI.Models
{
    public class Order
    {
        #region Properties
        /// <summary>
        /// CosmoDB ID - will be autogenerated
        /// </summary>
        [BsonId(IdGenerator = typeof(StringObjectIdGenerator))]
        public string Id {get;set;}

        /// <summary>
        /// Email address of the customer
        /// </summary>
        [BsonElement("EmailAddress")]
        [BsonRequired]
        public string EmailAddress {get;set;}

        /// <summary>
        /// Preferred Language of the customer
        /// </summary>
        [BsonElement("PreferredLanguage")]
        public string PreferredLanguage {get;set;}

        /// <summary>
        /// Product ordered by the customer
        /// </summary>
        [BsonElement("Product")]
        public string Product {get;set;}

        /// <summary>
        /// Order total
        /// </summary>
        [BsonElement("Total")]
        public double Total {get;set;}

        /// <summary>
        /// Source backend e.g. App Service, Container instance, K8 cluster etc
        /// </summary>
        [BsonElement("Source")]
        public string Source {get;set;}

        /// <summary>
        /// Order Status
        /// </summary>
        [BsonElement("Status")]
        [BsonRequired]
        public string Status {get;set;}
        #endregion
    }
}